server.port=5000
server.address=0.0.0.0
spring.application.name=api-rest-sincrono
management.endpoints.web.exposure.include=health,info
logging.level.com.example=INFO

# Desativa auto-config problemático do springdoc em alguns casos
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true